name: Matrix Fail Fast Example
on:
  push:

jobs:
  test-matrix:
    strategy:
      fail-fast: true
      matrix:
        node-version: [16, 18, 20]
        os: [ubuntu-latest, windows-latest]
    name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Print version and simulate failure on Node 18 + Windows
        run: |
          node -v
          if [[ "${{ matrix.node-version }}" == "18" && "${{ matrix.os }}" == "windows-latest" ]]; then
            echo "Simulating failure on Node 18 + Windows"
            exit 1
          fi
        shell: bash
