name: Matrix Fail Fast Serial and Parallel Example
on:
  push:

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: First job
        run: echo "Job 1 (serial start)"

  job-2-and-3:
    needs: job-1
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        job-name: [job-2, job-3]
    name: ${{ matrix.job-name }}
    steps:
      - name: ${{ matrix.job-name }}
        run: |
          echo "${{ matrix.job-name }} (parallel)"
          # 模拟 job-3 失败
          if [[ "${{ matrix.job-name }}" == "job-3" ]]; then
            echo "Simulate failure"
            exit 1
          fi

  job-4:
    needs: [job-2-and-3]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Last job
        run: echo "Job 4 (serial end)"
