
name: First Fail, Second Always with False Condition
on:
  push:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Failure
        run: exit 1   # 故意失败

  second-job:
    runs-on: ubuntu-latest
    needs: [first-job]
    if: ${{ always() && true && success()}}   # always() 总是判断，但条件为 false
    steps:
      - name: This step will not run
        run: echo "你不会看到这句话，因为条件恒为 false"
