
name: first Success, Second Condition False with success()
on:
  push:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Success
        run: echo "第一个 job 成功"

  second-job:
    runs-on: ubuntu-latest
    needs: [first-job]
    if: ${{ startsWith('hello', 'world') }}  && success()  # 这是一个简单表达式，总是 false
    steps:
      - name: This step will not run
        run: echo "你不会看到这句话，因为条件恒为 false"
