name: Only Condition and Needs Example
on:
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Failure
        run: exit 1     # 故意失败

  second-job:
    runs-on: ubuntu-latest
    needs: [first-job]
    if: ${{ 1 + 1 == 2 }}   # 只根据自己的条件运行，不管前一个job成败
    steps:
      - name: Run Only If Condition True
        run: echo "This job runs because 1+1=2"
