name: Android Build  
on:  
  push:  
    branches: [ main ]  
jobs:  
  checkout-and-stash:  
    runs-on: android-global-aws  
    steps:  
    - name: Checkout code  
      uses: checkout@4  
      with:  
        repository: mobile/reference-android-plugin  
    - name: Look  
      run: ls -al  

  unstash:  
    runs-on: android-small-aws  
    needs:  
      - checkout-and-stash  
    steps:  
    - name: Check  
      run: ls -al  
