name: Android Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checkout-and-stash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Look
        run: ls -al
      - name: Force Fail
        run: exit 1   # 故意失败

  unstash:
    runs-on: ubuntu-latest
    needs: [checkout-and-stash]
    if: always()                # 无论前一个 job 成功还是失败都会运行
    steps:
      - name: Check
        run: ls -al
