name: Only Condition and Needs Example
on:
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Failure
        run: exit 1     # 故意失败

  second-job:
    runs-on: ubuntu-latest
    needs: [first-job]
    if: ${{ env.MY_CONDITION == 'run' }}    # 只在环境变量满足时运行
    env:
      MY_CONDITION: run                     # 这里设置环境变量
    steps:
      - name: Run Only If Env Condition
        run: echo "第二个 job 因为环境变量条件满足而运行"
