name: Simple Condition and Needs Example
on:
  push:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Failure
        run: exit 1     # 故意失败

  second-job:
    runs-on: ubuntu-latest
    needs: [first-job]
    if: ${{ true }}    # 简单条件，始终满足
    steps:
      - name: Run Because Condition Is True
        run: echo "第二个 job 因为条件为 true 而运行"
