name: Android Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checkout-and-stash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Look
        run: ls -al
      - name: Force Fail
        run: exit 1   # 让 job 失败

  unstash:
    runs-on: ubuntu-latest
    needs: [checkout-and-stash]
    if: failure()                # 仅在前一个 job 失败时才运行
    steps:
      - name: Only run if previous failed
        run: echo "Previous job failed, running recovery steps."
