name: Test Cancelled Condition
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate long running job
        run: sleep 300  # 让 job 持续运行，方便你手动取消

  after_cancelled:
    runs-on: ubuntu-latest
    needs: [build]
    if: cancelled()   # 只有前一个 job 被取消时才运行
    steps:
      - name: Notify cancelled
        run: echo "The previous job was cancelled!"
