name: First Fail, Second Condition False
on:
  push:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Failure
        run: exit 1     # 故意失败

  second-job:
    runs-on: ubuntu-latest
    needs: [first-job]
    if: ${{ false }}    # 条件不满足，第二个 job 不会执行
    steps:
      - name: This step will not run
        run: echo "你不会看到这句话，因为条件是 false"
